const TrendingList = [
    {
        id:"1",
        imgUrl:"https://covers.openlibrary.org/b/olid/OL8833344M-M.jpg",
        bookTitle:"Murder on the Orient Express",
        bookUrl:"#action1",
        bookAuthor:"Agatha Christie",
        authorUrl:"#action1",
        published:"1933",
        editions:"153",
        editionsUrl:"#action1",
        bookStatus:"Borrow",
        btnStyle:"active-btn"
    },
    {
        id:"2",
        imgUrl:"https://openlibrary.org/images/icons/avatar_book-sm.png",
        bookTitle:"Existence, relatedness, and growth",
        bookUrl:"#action2",
        bookAuthor:"Clayton P. Alderfer",
        authorUrl:"#action2",
        published:"1972",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
        btnStyle:"notActive-btn"
    },
    {
        id:"3",
        imgUrl:"https://covers.openlibrary.org/b/id/4770205-M.jpg",
        bookTitle:"The Letters to the Thessalonians (Pillar New Testament Commentary)",
	    bookUrl:"#action2",
        bookAuthor:"Gene L. Green",
	    authorUrl:"#action2",
        published:"2002",
        editions:"2",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
 	    btnStyle:"notActive-btn"
    },
    {
        id:"4",
        imgUrl:"https://covers.openlibrary.org/b/id/1004197-M.jpg",
        bookTitle:"Pünktchen und Anton. Ein Roman für Kinder. ( Ab 10 J.)",
	    bookUrl:"#action2",
        bookAuthor:"Erich Kästner",
	    authorUrl:"#action2",
        published:"2002",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
        btnStyle:"notActive-btn"
    },
    {
        id:"5",
        imgUrl:"https://covers.openlibrary.org/b/id/12539702-M.jpg",
        bookTitle:"Atomic Habits",
	    bookUrl:"#action2",
        bookAuthor:"James Clear",
	    authorUrl:"#action2",
        published:"2018",
        editions:"30",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
        btnStyle:"notActive-btn"
    },
    {
        id:"6",
        imgUrl:"https://openlibrary.org/images/icons/avatar_book-sm.png",
        bookTitle:"Perubahan perilaku sosial pasca krisis",
	    bookUrl:"#action2",
        bookAuthor:"Unknown author",
	    authorUrl:"#action",
        published:"2004",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
        btnStyle:"notActive-btn"
    },
    {
        id:"7",
        imgUrl:"https://openlibrary.org/images/icons/avatar_book-sm.png",
        bookTitle:"Pashto urdu bol chal ki asan kitab",
	    bookUrl:"#action2",
        bookAuthor:"Makhdum Sabri",
	    authorUrl:"#action",
        published:"unKnown",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
        btnStyle:"notActive-btn"
    },
    {
        id:"8",
        imgUrl:"https://covers.openlibrary.org/b/olid/OL23421746M-M.jpg",
        bookTitle:"Ruskin--Sesame and lilies",
	    bookUrl:"#action2",
        bookAuthor:"Peter Henry Pearson",
	    authorUrl:"#action",
        published:"1914",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Read",
        btnStyle:"active-btn"
    },
    {
        id:"9",
        imgUrl:"https://covers.openlibrary.org/b/olid/OL25418275M-M.jpg",
        bookTitle:"The 48 Laws of Power",
	    bookUrl:"#action2",
        bookAuthor:"Robert Greene",
	    authorUrl:"#action",
        published:"1998",
        editions:"26",
        editionsUrl:"#action1",
        bookStatus:"Borrow",
        btnStyle:"active-btn"
    },
    {
        id:"10",
        imgUrl:"https://covers.openlibrary.org/b/olid/OL5101635M-M.jpg",
        bookTitle:"An introduction to town planning techniques",
	    bookUrl:"#action2",
        bookAuthor:"Margaret Roberts",
	    authorUrl:"#action",
        published:"1974",
        editions:"4",
        editionsUrl:"#action1",
        bookStatus:"Borrow",
        btnStyle:"active-btn"
    }
    ,
    {
        id:"11",
        imgUrl:"https://covers.openlibrary.org/b/olid/OL27351482M-M.jpg",
        bookTitle:"The Subtle Art of Not Giving a F*ck",
	    bookUrl:"#action2",
        bookAuthor:"Mark Manson",
	    authorUrl:"#action",
        published:"2016",
        editions:"37",
        editionsUrl:"#action1",
        bookStatus:"Preview",
        btnStyle:"preview-btn"
    },
    {
        id:"12",
        imgUrl:"https://openlibrary.org/images/icons/avatar_book-sm.png",
        bookTitle:"I never grew up",
	    bookUrl:"#action2",
        bookAuthor:"Cobina Wright",
	    authorUrl:"#action2",
        published:"1952",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
 	    btnStyle:"notActive-btn"
    },
    {
        id:"13",
        imgUrl:"https://covers.openlibrary.org/b/id/12539702-M.jpg",
        bookTitle:"Atomic Habits",
	    bookUrl:"#action2",
        bookAuthor:"James Clear",
	    authorUrl:"#action2",
        published:"2018",
        editions:"30",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
 	    btnStyle:"notActive-btn"
    },
    {
        id:"14",
        imgUrl:"https://openlibrary.org/images/icons/avatar_book-sm.png",
        bookTitle:"Trail driving days",
	    bookUrl:"#action2",
        bookAuthor:"Dee Alexander Brown",
	    authorUrl:"#action2",
        published:"1952",
        editions:"3",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
 	    btnStyle:"notActive-btn"
    },
    {
        id:"15",
        imgUrl:"https://covers.openlibrary.org/b/olid/OL6116087M-M.jpg",
        bookTitle:"Man's search for himself",
	    bookUrl:"#action2",
        bookAuthor:"Rollo May",
	    authorUrl:"#action2",
        published:"153",
        editions:"16",
        editionsUrl:"#action1",
        bookStatus:"Borrow",
 	    btnStyle:"active-btn"
    },
    {
        id:"16",
        imgUrl:"https://openlibrary.org/images/icons/avatar_book-sm.png",
        bookTitle:"Economy of Somalia",
	    bookUrl:"#action2",
        bookAuthor:"Frederic P. Miller",
	    authorUrl:"#action2",
        published:"2010",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
 	    btnStyle:"notActive-btn"
    },
    {
        id:"17",
        imgUrl:"https://covers.openlibrary.org/b/olid/OL27099073M-M.jpg",
        bookTitle:"A Court of Thorns and Roses",
	    bookUrl:"#action2",
        bookAuthor:"Sarah J. Maas",
	    authorUrl:"#action2",
        bookAuthor2:"Sarah J. Maas",
	    authorUrl2:"#action2",
        published:"2015",
        editions:"22",
        editionsUrl:"#action1",
        bookStatus:"Join Waitlist",
 	    btnStyle:"active-btn"
    },
    {
        id:"18",
        imgUrl:"https://covers.openlibrary.org/b/olid/OL35502617M-M.jpg",
        bookTitle:"Two Bottles of Relish",
	    bookUrl:"#action2",
        bookAuthor:"Lord Dunsany",
	    authorUrl:"#action2",
        published:"2016",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Checked Out",
 	    btnStyle:"notActive-btn"
    },
    {
        id:"19",
        imgUrl:"https://openlibrary.org/images/icons/avatar_book-sm.png",
        bookTitle:"I led three lives",
	    bookUrl:"#action2",
        bookAuthor:"Herbert Arthur Philbrick",
	    authorUrl:"#action2",
        published:"1952",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
 	    btnStyle:"notActive-btn"
    }
    ,
    {
        id:"20",
        imgUrl:"https://covers.openlibrary.org/b/id/11942032-M.jpg",
        bookTitle:"Ace the Data Science Interview",
	    bookUrl:"#action2",
        bookAuthor:"Nick Singh",
	    authorUrl:"#action2",
        bookAuthor2:"Kevin Huo",
        authorUrl2:"#action1",
        published:"2021",
        editions:"1",
        editionsUrl:"#action1",
        bookStatus:"Not in Library",
 	    btnStyle:"notActive-btn"
    }
];

export default TrendingList;